import { mkdir, readdir, readFile, writeFile } from "node:fs/promises"
import { createRequire } from "node:module"
import { dirname, join, relative, resolve } from "node:path"

type MonacoExtraLib = {
	content: string
	filePath: string
}

const require = createRequire(import.meta.url)
const playgroundRoot = resolve(import.meta.dirname, "..")
const workspaceRoot = resolve(playgroundRoot, "../..")
const outputPath = join(playgroundRoot, "src/generated/monaco-extra-libs.ts")

const resolvePackageRoot = (specifier: string, paths: string[]) => {
	const entry = require.resolve(specifier, { paths })
	const packageIndex = entry.lastIndexOf(`/node_modules/${specifier}/`)

	if (packageIndex >= 0) {
		return entry.slice(0, packageIndex + `/node_modules/${specifier}`.length)
	}

	const scopedIndex = entry.lastIndexOf(`/node_modules/${specifier.split("/")[0]}/`)
	if (specifier.startsWith("@") && scopedIndex >= 0) {
		return entry.slice(0, scopedIndex + `/node_modules/${specifier}`.length)
	}

	return dirname(entry)
}

const readIfExists = async (path: string) => {
	try {
		return await readFile(path, "utf8")
	} catch (error) {
		throw new Error(`Missing declaration input: ${path}`, { cause: error })
	}
}

const collectFiles = async (
	directory: string,
	predicate: (path: string) => boolean,
): Promise<string[]> => {
	const entries = await readdir(directory, { withFileTypes: true })
	const files = await Promise.all(
		entries.map(async (entry) => {
			const path = join(directory, entry.name)

			if (entry.isDirectory()) {
				return collectFiles(path, predicate)
			}

			return predicate(path) ? [path] : []
		}),
	)

	return files.flat().sort()
}

const toNodeModulePath = (packageName: string, packageRoot: string, filePath: string) =>
	`file:///node_modules/${packageName}/${relative(packageRoot, filePath).replaceAll("\\", "/")}`

const addSourceFile = async (
	libs: MonacoExtraLib[],
	packageName: string,
	packageRoot: string,
	filePath: string,
) => {
	const content = await readIfExists(filePath)
	const fileUrl = toNodeModulePath(packageName, packageRoot, filePath)
	libs.push({ content, filePath: fileUrl })

	if (fileUrl.endsWith(".d.ts")) {
		libs.push({ content, filePath: fileUrl.replace(/\.d\.ts$/, ".ts") })
	}

	if (fileUrl.endsWith(".d.mts")) {
		libs.push({ content, filePath: fileUrl.replace(/\.d\.mts$/, ".mjs") })
	}
}

const regexWandTypes = await readIfExists(
	join(workspaceRoot, "packages/regex-wand/dist/index.d.ts"),
)
const magicRoot = resolvePackageRoot("magic-regexp", [playgroundRoot])
const arkRoot = resolvePackageRoot("arkregex", [playgroundRoot])
const arkUtilRoot = resolvePackageRoot("@ark/util", [arkRoot])
const typeLevelRegexpRoot = resolvePackageRoot("type-level-regexp", [magicRoot])

const libs: MonacoExtraLib[] = [
	{
		content: regexWandTypes,
		filePath: "file:///node_modules/regex-wand/index.d.ts",
	},
	{
		content: 'export * from "./dist/index.d.mts"\n',
		filePath: "file:///node_modules/magic-regexp/index.d.ts",
	},
	{
		content: 'export { regex, type Regex } from "./out/index.ts"\n',
		filePath: "file:///node_modules/arkregex/index.d.ts",
	},
	{
		content: 'export * from "./out/index.ts"\n',
		filePath: "file:///node_modules/@ark/util/index.d.ts",
	},
]

await addSourceFile(libs, "magic-regexp", magicRoot, join(magicRoot, "dist/index.d.mts"))

for (const file of await collectFiles(join(magicRoot, "dist"), (path) => {
	const fileName = path.split("/").at(-1)
	return fileName?.startsWith("magic-regexp-") && path.endsWith(".d.mts")
})) {
	await addSourceFile(libs, "magic-regexp", magicRoot, file)
}

await addSourceFile(
	libs,
	"type-level-regexp",
	typeLevelRegexpRoot,
	join(typeLevelRegexpRoot, "regexp.d.ts"),
)
await addSourceFile(
	libs,
	"type-level-regexp",
	typeLevelRegexpRoot,
	join(typeLevelRegexpRoot, "dist/regexp.d.ts"),
)

for (const file of await collectFiles(join(arkRoot, "out"), (path) =>
	path.endsWith(".d.ts"),
)) {
	await addSourceFile(libs, "arkregex", arkRoot, file)
}

for (const file of await collectFiles(join(arkUtilRoot, "out"), (path) =>
	path.endsWith(".d.ts"),
)) {
	await addSourceFile(libs, "@ark/util", arkUtilRoot, file)
}

const generated = `// Generated by scripts/generate-monaco-extra-libs.ts.
// Do not hand-edit. These declarations come from the built package and installed deps.
// biome-ignore-all lint/suspicious/noTemplateCurlyInString: declaration text intentionally contains TypeScript template literal syntax.

export type MonacoExtraLib = {
\tcontent: string
\tfilePath: string
}

export const monacoExtraLibs = ${JSON.stringify(libs, null, "\t")} satisfies MonacoExtraLib[]
`

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, generated)
